ALTER TABLE PEDIDOS DROP CONSTRAINT FORNECEDORES_PEDIDOS_FK;
ALTER TABLE PEDIDOS DROP CONSTRAINT CLIENTES_PEDIDOS_FK;

DROP TABLE FORNECEDORES;
DROP TABLE CLIENTES;
DROP TABLE PEDIDOS;
DROP TABLE PRODUTOS;
DROP TABLE FUNCIONARIO;
DROP TABLE EMPRESA;

DROP SEQUENCE PEDIDOS_CODIGO_PEDIDO_SEQ;
DROP SEQUENCE PRODUTOS_CODIGO_PRODUTO_SEQ;

CREATE TABLE FORNECEDORES (
                CNPJ VARCHAR2(14) NOT NULL,
                RAZAO_SOCIAL VARCHAR2(255) NOT NULL,
                NOME_FANTASIA VARCHAR2(255) NOT NULL,
                CONSTRAINT FORNECEDORES_PK PRIMARY KEY (CNPJ)
);

CREATE TABLE CLIENTES (
                CPF VARCHAR2(11) NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                TELEFONE VARCHAR2(255) NOT NULL,
                ENDERECO VARCHAR2(255) NOT NULL,
                CONSTRAINT CLIENTES_PK PRIMARY KEY (CPF)
);

CREATE TABLE FUNCIONARIO (
                CPF VARCHAR2(11) NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                CONSTRAINT FUNCIONARIO_PK PRIMARY KEY (CPF)
);

CREATE TABLE EMPRESA (
                CNPJ VARCHAR2(14) NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                RAZAOSOCIAL VARCHAR2(255) NOT NULL,
                CONSTRAINT EMPRESA_PK PRIMARY KEY (CNPJ)
);


CREATE SEQUENCE PEDIDOS_CODIGO_PEDIDO_SEQ;

CREATE TABLE PEDIDOS (
                CODIGO_PEDIDO NUMBER NOT NULL,
                DATA_PEDIDO DATE NOT NULL,
                CPF VARCHAR2(11) NOT NULL,
                CNPJ VARCHAR2(14) NOT NULL,
                CONSTRAINT PEDIDOS_PK PRIMARY KEY (CODIGO_PEDIDO)
);


CREATE SEQUENCE PRODUTOS_CODIGO_PRODUTO_SEQ;

CREATE TABLE PRODUTOS (
                CODIGO_PRODUTO NUMBER NOT NULL,
                DESCRICAO_PRODUTO VARCHAR2(255) NOT NULL,
                CONSTRAINT PRODUTOS_PK PRIMARY KEY (CODIGO_PRODUTO)
);


ALTER TABLE PEDIDOS ADD CONSTRAINT FORNECEDORES_PEDIDOS_FK
FOREIGN KEY (CNPJ)
REFERENCES FORNECEDORES (CNPJ)
NOT DEFERRABLE;

ALTER TABLE PEDIDOS ADD CONSTRAINT CLIENTES_PEDIDOS_FK
FOREIGN KEY (CPF)
REFERENCES CLIENTES (CPF)
NOT DEFERRABLE;
