DROP TABLE EMPRESA;
DROP TABLE HOLERITE;
DROP TABLE FUNCIONARIO;


CREATE TABLE EMPRESA (
                CNPJ VARCHAR2(14) NOT NULL,
                RAZAO_SOCIAL VARCHAR2(255) NOT NULL,
                NOME_FANTASIA VARCHAR2(255) NOT NULL,
                CONSTRAINT EMPRESA_PK PRIMARY KEY (CNPJ)
);

CREATE TABLE FUNCIONARIO (
                CPF VARCHAR2(11) NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                CONSTRAINT FUNCIONARIO_PK PRIMARY KEY (CPF)
);

CREATE TABLE HOLERITE (
                CODIGO NUMBER NOT NULL,
                CPF VARCHAR2(11) NOT NULL,
                CNPJ VARCHAR2(14) NOT NULL,
                SALARIOBRUTO FLOAT(9) NOT NULL,
                FGTS FLOAT(9) NOT NULL,
                IRPF FLOAT(9) NOT NULL,
                SALARIOLIQUIDO FLOAT(9) NOT NULL,
                CONSTRAINT HOLERITE_PK PRIMARY KEY (CODIGO)
);

ALTER TABLE HOLERITE ADD CONSTRAINT FUNCIONARIO_HOLERITE_FK
FOREIGN KEY (CPF)
REFERENCES FUNCIONARIO (CPF)
NOT DEFERRABLE;

ALTER TABLE HOLERITE ADD CONSTRAINT EMPRESA_HOLERITE_FK
FOREIGN KEY (CNPJ)
REFERENCES EMPRESA (CNPJ)
NOT DEFERRABLE;